import { chromium } from "playwright";
import { startSerwera } from "../tools/serwer.mjs";
import fs from "node:fs";
const OUT = "tests/zrzuty/"; fs.mkdirSync(OUT, { recursive: true });
const s = await startSerwera(4312);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const bledy = [];
p.on("pageerror", (e) => bledy.push(String(e)));
p.on("console", (m) => { if (m.type() === "error") bledy.push(m.text()); });
p.on("response", (r) => { if (r.status() >= 400) bledy.push(r.status() + " " + r.url()); });
await p.goto(s.url, { waitUntil: "networkidle" });
await p.waitForTimeout(1000);
await p.evaluate(() => document.getElementById("gabinet").scrollIntoView());
await p.waitForTimeout(2500);
await p.screenshot({ path: OUT + "gabinet.png" });
 await p.evaluate(() => scrollBy(0, 560));
 await p.waitForTimeout(2200);
 await p.screenshot({ path: OUT + "gabinet-dol.png" });
const ile = await p.locator(".gabinet__karta").count();
const widoczne = await p.locator(".gabinet__karta.widoczna").count();
console.log("kart:", ile, "ujawnionych:", widoczne);
const tel = await b.newPage({ viewport: { width: 390, height: 844 } });
await tel.goto(s.url, { waitUntil: "networkidle" });
await tel.evaluate(() => document.getElementById("gabinet").scrollIntoView());
await tel.waitForTimeout(2500);
await tel.screenshot({ path: OUT + "gabinet-telefon.png", fullPage: false });
const m = await tel.evaluate(() => ({ szer: document.documentElement.scrollWidth, okno: innerWidth }));
console.log("telefon:", JSON.stringify(m), m.szer <= m.okno + 1 ? "OK" : "PRZEWIJA");
console.log("bledy:", bledy.length ? bledy.slice(0,4) : "brak");
await b.close(); s.stop();
