import { chromium } from "playwright";
import { startSerwera } from "../tools/serwer.mjs";
import fs from "node:fs";
const OUT = "tests/zrzuty/"; fs.mkdirSync(OUT, { recursive: true });
const s = await startSerwera(4317);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 980 } });
await p.goto(s.url + "szkolenia.html", { waitUntil: "networkidle" });
await p.waitForSelector(".karta.widoczna");
await p.waitForTimeout(1600);
await p.screenshot({ path: OUT + "katalog.png" });
await p.click('.filtr__btn[data-grupa="kontakt"]');
await p.waitForTimeout(900);
await p.screenshot({ path: OUT + "katalog-filtr.png" });
await p.goto(s.url + "szkolenie.html?id=inteligencja-komunikacji", { waitUntil: "networkidle" });
await p.waitForTimeout(900);
await p.screenshot({ path: OUT + "szkolenie.png" });
await b.close(); s.stop();
console.log("zrzuty gotowe");
